# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: forge Task
    init: "curl -L https://foundry.paradigm.xyz | bash" # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: "source /home/gitpod/.bashrc && foundryup"

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
